name: AutoMerge

on:
  push:
    branches:
      - release/*

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Git (Optional)
        # You can remove this step if you already have Git configured locally
        run: |
          git config user.name "Hoai Tran"
          git config user.email "hoai.nart.dev@gmail.com"

      - name: Fetch updates (assuming remote is named 'origin')
        run: |
          git fetch --no-tags --prune --depth=1 origin
          ls -la
          echo github.ref: ${{ github.ref }}

      - name: Checkout main branch
        run: |
          git checkout main

      - name: Attempt to merge release branch (handling unrelated histories)
        run: |
          git merge --no-ff --allow-unrelated-histories ${{ github.ref }}
          MERGE_STATUS=$?

          if [ $MERGE_STATUS -eq 0 ]; then
            git commit -m "Merge branch ${{ github.ref }} (unrelated histories)"
            git push origin main
            echo "Merge successful (unrelated histories handled)."
          elif [[ $MERGE_STATUS -eq 1 ]]; then
            echo "Merge conflicts detected. Please resolve them manually and commit the changes."
            exit 1
          else
            echo "An unexpected error occurred during the merge (status: $?)."
            exit 1
          fi
