name: AutoMerge
'on':
  push:
    branches:
      - release/*
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Git
        run: |
          git config user.name "Hoai Tran"
            git config user.email "hoai.nart.dev@gmail.com"
      - name: Attempt to merge release branch into main
        run: |
          git checkout main
          git pull origin main

          # Attempt to merge the release branch into main
          git merge --no-commit --no-ff ${{ github.ref }}

          if [ $? -eq 0 ]; then
            # Commit the merge if successful
            git commit -m "Merge branch ${{ github.ref }}"
          else
            echo "Merge conflicts detected. Please resolve them manually."
            exit 1
          fi
      - name: Push change if merge was successful
        if: success()
        run: |
          git push origin main
          echo "${{ job.status }}"
